version: '2.4'

services:
  app:
    build:
      context: containers/fpm
    working_dir: /var/www
    tmpfs:
      - /tmp:rw,nodev,noexec,nosuid

  webserver:
    image: nginx:mainline-alpine
    healthcheck:
      test: wget -q --spider localhost/status
      timeout: 3s
      interval: 300s
      start_period: 5s
      retries: 3
