version: '2.4'

services:
  app:
    env_file:
      - .env
    volumes:
      - .:/var/www
      - ./containers/fpm/dev/custom.conf:/usr/local/etc/php-fpm.d/custom.conf:ro
    depends_on:
      mailcatcher:
        condition: service_started
      tokenstore:
        condition: service_started

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 25
      - 80

  tokenstore:
    image: redis:alpine@sha256:50899ea1ceed33fa03232f3ac57578a424faa1742c1ac9c7a7bdb95cdf19b858

  webserver:
    volumes:
      - ./containers/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80
    depends_on:
      app:
        condition: service_started
