services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Action\:
    resource: '../src/Action/'
    tags:
      - { name: controller.service_arguments }

  NevStokes\SplitTokens\Repository\UserTokenRepository:
    class: NevStokes\SplitTokens\Repository\InMemoryUserTokenRepository

  NevStokes\SplitTokens\Token\TokenGenerator:
    arguments:
      $signingKey: '%token.signing_key%'

  NevStokes\SplitTokens\Token\TokenValidator:
    arguments:
      $signingKey: '%token.signing_key%'
