services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Action\:
    resource: '../src/Action/'
    tags:
      - { name: controller.service_arguments }

  Redis:
    class: Redis
    lazy: true
    calls:
      - method: connect
        arguments:
          - '%redis.host%'

  NevStokes\SplitTokens\Repository\UserTokenRepository:
    class: NevStokes\SplitTokens\Repository\RedisUserTokenRepository
    arguments:
      $prefix: '%redis.token_prefix%'

  NevStokes\SplitTokens\Token\TokenGenerator:
    arguments:
      $signingKey: '%token.signing_key%'

  NevStokes\SplitTokens\Token\TokenValidator:
    arguments:
      $signingKey: '%token.signing_key%'
